---
abstract: 'PDL bindings to some BLAS and LAPACK library routines'
author:
  - 'Chris Marshall <chm@cpan.org>'
build_requires:
  PDL: 0
configure_requires:
  PDL: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDL-LinearAlgebra
no_index:
  directory:
    - t
    - inc
requires:
  PDL: 0
resources:
  homepage: http://pdl.perl.org/
version: 0.08_01
